version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: TEST
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
            - "~/.cache/yarn"
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
        name: Update yarn lockfile
        command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test:prod
      - run:
          name: Build
          command: yarn build
       - store_artifacts:
          path: ./dist
          destination: dist
      - store_artifacts:
          path: ./coverage
          destination: coverage
      - store_artifacts:
          path: ./docs
          destination: docs
